# Generated by Django 3.1.1 on 2020-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productofamilia',
            name='familia',
            field=models.CharField(choices=[('O', 'OTROS'), ('A', 'ALIMENTOS PERECEDEROS Y NO PERECEDEROS'), ('B', 'BEBIDAS'), ('AA', 'ARTICULOS DE ASEO'), ('PB', 'PRODUCTOS DE BAZAR')], default='O', help_text='La categoria a la que pertenece el producto', max_length=2),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rubro',
            field=models.CharField(choices=[('O', 'OTROS'), ('A', 'ALIMENTOS PERECEDEROS Y NO PERECEDEROS'), ('B', 'BEBIDAS'), ('AA', 'ARTICULOS DE ASEO'), ('PB', 'PRODUCTOS DE BAZAR')], default='O', max_length=2),
        ),
    ]
