# Generated by Django 3.1.1 on 2020-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_auto_20201013_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_familia',
            field=models.CharField(choices=[('O', 'OTROS'), ('A', 'ALIMENTOS PERECEDEROS Y NO PERECEDEROS'), ('B', 'BEBIDAS'), ('AA', 'ARTICULOS DE ASEO'), ('PB', 'PRODUCTOS DE BAZAR')], default='O', max_length=2),
        ),
        migrations.DeleteModel(
            name='ProductoFamilia',
        ),
    ]
